"""empty message

Revision ID: 075861239388
Revises: 
Create Date: 2018-06-26 15:21:00.458731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075861239388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
